### ISSUE TITLE
docs: document the C++ RadosParquetFileFormat API

### ISSUE THREAD

**Issue by JayjeetAtGithub** [uccross/skyhookdm-arrow#98]
The Arrow documentation by built by following the steps given [here](https://github.com/apache/arrow/blob/master/docs/source/developers/documentation.rst). After the documentation is up and running in the local, the next step is to look at the [current Arrow README ](https://github.com/uccross/arrow/blob/rados-dataset-dev/cpp/src/arrow/adapters/arrow-rados-cls/README.md)and try porting it to read the docs.

**Comment by prondubuisi** [comment]
Hello, @JayjeetAtGithub @jlefevre Is this project still looking for a Mentee? 

Also since we have just 7 days left to submit proposals I would need some clarity on what needs to be done.

From Looking around, this is what I think the Project requires

1) Build the [arrow docs](https://github.com/apache/arrow/blob/master/docs/source/developers/documentation.rst) locally

2) Port the docs to [readthedocs](https://readthedocs.org/)

My questions are as follows;

1) Why do we need to build arrows doc locally before porting it? Are there any benefits to this? Is it possible to port the docs without building it locally?

2) Which of the docs should be ported? The [ arrow docs](https://github.com/apache/arrow/blob/master/docs/source/developers/documentation.rst) or its[ uccross fork](https://github.com/uccross/arrow/blob/rados-dataset-dev/cpp/src/arrow/adapters/arrow-rados-cls/README.md)?

Thanks

**Comment by prondubuisi** [comment]
I have been able to set up the Project locally, what are the next steps @JayjeetAtGithub 

![image](https://user-images.githubusercontent.com/22311928/116962547-27f35200-ac9e-11eb-98ac-68530a966e13.png)

**Comment by JayjeetAtGithub** [comment]
> Why do we need to build arrows doc locally before porting it? Are there any benefits to this? Is it possible to port the docs without building it locally?

It should be fine without building locally, but to be able to verify that the docstrings in C++ get converted to docs correctly in the local machine should be good.

> Which of the docs should be ported? The arrow docs or its uccross fork?

The arrow docs are the documentation of the upstream arrow project. We intend to merge skyhook with the upstream arrow project, so we would like to present our documentation in the uccross fork in the format apache arrow comm. does.

**Comment by prondubuisi** [comment]
Sounds good and Interesting. Thanks for the response @JayjeetAtGithub

**Comment by JayjeetAtGithub** [comment]
this is now tracked by #158
